FROM	nginx

RUN		apt update -y && apt upgrade -y \
&& apt install -y php-fpm php-cli

COPY	./nginx.conf /etc/nginx
RUN		usermod -a -G www-data nginx
RUN 	php-fpm8.2

CMD ["sh", "-c", "php-fpm8.2 --nodaemonize & nginx-debug -g 'daemon off;'"]
